spring:
  batch:
    job:
      enabled: false

filetask:
  input:
    files:
      - E:\\testdata\\input\\data1\\testdata1.txt
      - E:\\testdata\\input\\data2\\testdata2.txt
      - E:\\testdata\\input\\data3\\testdata3.txt
  midlle: E:\\testdata\\middle
  output: E:\\testdata\\output
  password: '{cipher}AQBxbQEdk4UwWJb1ZZ4DYzKI1SPDrTpKaEExHmP6I830cMgr3bwc/f66+RZVItKnMwr4FsHskHEy0b7JIpgK16TxGDB61irdog79hVIsDn7E9A9oXdZsjcec2vZ0ihTmL293G2Q1iBh/6bVqX+hbzWcBija26O2WJtlaot265QPYnd9QoZaxP6ybPSVHIl9GEvIj3NHJp3VuPZcZQWOir3LUMZUWbeCB2VdiSBbekokJlqLNY1JGHn2yh32ucqQ40dIq6WTQ5Nv87GsIu+yUr9NoJGQP+zlg0JF1dF7Z9FskV0LBRTQ3k/8SVE/u0qpYk6hCzKa/S98bycCbq8a9LZVeTsxF1g/pGGAVAJ8UKClDFq5x8FYyMoniKHvnre47EwE='