spring:
  batch:
    job:
      enabled: false

filetask:
  input:
    files:
      - E:\\testdata\\input\\data1\\testdata1.txt
      - E:\\testdata\\input\\data2\\testdata2.txt
      - E:\\testdata\\input\\data3\\testdata3.txt
  midlle: E:\\testdata\\middle
  output: E:\\testdata\\output